---
- name: "{{ action | upper }} NAT"
  fortios_firewall_policy:
    state: present
    firewall_policy:
      name: "NAT-TO-INTERNET"
      policyid: "{{ id }}"
      action: accept
      srcintf: "{{ srcintf }}"
      dstintf: "{{ dstintf }}"
      srcaddr: "{{ srcaddr }}"
      dstaddr: "{{ dstaddr }}"
      service: "{{ service }}"
      schedule: "{{ schedule }}"
      nat: "enable"
  when: action == "add" or action == "configure"


- name: "{{ action | upper }} NAT Interface"
  fortios_firewall_policy:
    state: present
    firewall_policy:
      policyid: "{{ id }}"
      srcintf: "{{ srcintf }}"
      status: "{{ action }}"
  when: action == "enable" or action == "disable"